# 3次元以上のtransposeの理解

In [2]:
import numpy as np

In [3]:
img = np.array([[[ 0, 1, 2],
                 [ 3, 4, 5],
                 [ 6, 7, 8]],

                [[ 9,10,11],
                 [12,13,14],
                 [15,16,17]]])

img = img.transpose(0, 2, 1)
print(img)

[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]]


---
<ポイント>

・ 軸(C, H, W)を意識する。  
・ まず、転置後のW要素を考える。  
・上記の問題では、transpose(0, 2, 1)で転置後のW軸に転置前のH軸がくる  
<br>
・転置前の一番上の行列のH軸は  [0, 3, 6]  これが転置後の最初の1行目にくる。(串刺しともいう)   
・転置後のH軸は転置前のW軸が来るので転置前の [0, 1, 2]　が転置後の最初の一行目になる　　　
・転置後のC軸は転置前のC軸のままなので [0, 9]がC軸の方向になる  

上記から転置後  
[0, 3. 6]  
[1, X, X]  
[2, X, X],

[9, X. X]  
[X, X, X]  
[X, X, X]  

あとは上記を他の要素でも対応するだけ

---

#　４次元のTranspose

In [4]:
img = np.array([
               [[[ 0, 1, 2],
                 [ 3, 4, 5],
                 [ 6, 7, 8]],

                [[ 9,10,11],
                 [12,13,14],
                 [15,16,17]]],

               [[[18,19,20],
                 [21,22,23],
                 [24,25,26]],

                [[27,28,29],
                 [30,31,32],
                 [33,34,35]]]
                ])

img = img.transpose(2, 3, 0, 1)
print(img)

[[[[ 0  9]
   [18 27]]

  [[ 1 10]
   [19 28]]

  [[ 2 11]
   [20 29]]]


 [[[ 3 12]
   [21 30]]

  [[ 4 13]
   [22 31]]

  [[ 5 14]
   [23 32]]]


 [[[ 6 15]
   [24 33]]

  [[ 7 16]
   [25 34]]

  [[ 8 17]
   [26 35]]]]


---
<ポイント>

・ 軸(N, C, H, W)を意識する。  
・ あとは３次元の転置と同じ考え！！
・ まず、転置後のW要素を考える。  
・上記の問題では、transpose(2, 3, 0, 1)で転置後のW軸に転置前のC軸がくる
<br>
・転置前の一番上の行列(0, C, H, W)のC軸は  [0, 9]  これが転置後の最初の1行目にくる。(串刺しともいう)   
・転置後のH軸は転置前のN軸が来るので転置前の [0, 18] 　が転置後の最初の一行目になる　　　
・転置後のC軸は転置前のW軸なので [0, 1, 2]がC軸の方向になる
・転置後のN軸は転置前のH軸なので [0, 3, 6]がC軸の方向になる  


上記から転置後  
[[[[ 0  9]  
   [18 X]]

  [[ 1 X]  
   [X X]]

  [[2  X]  
   [X X]]]
<br>

 [[[ 3 X]  
   [X X]]  

  [[X X]  
   [X X]]  

  [[X  X]  
   [X X]]]  


 [[[6 X]  
   [X X]]  

  [[X  X]  
   [X X]]  

  [[X  X]  
   [X X]]]]  
あとは上記を他の要素でも対応するだけ

---



In [7]:
# 3次元のslicing結果の確認
img = np.array([[[ 0, 1, 2],
                 [ 3, 4, 5],
                 [ 6, 7, 8]],

                [[ 9,10,11],
                 [12,13,14],
                 [15,16,17]]])

img[:, 0:2, 0:2]

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

In [69]:
col = np.zeros((1, 2, 2, 2, 2, 2))

In [70]:
col[:, :, 0, 0, :, :] = img[:, 0:2, 0:2]

In [71]:
col

array([[[[[[ 0.,  1.],
           [ 3.,  4.]],

          [[ 0.,  0.],
           [ 0.,  0.]]],


         [[[ 0.,  0.],
           [ 0.,  0.]],

          [[ 0.,  0.],
           [ 0.,  0.]]]],



        [[[[ 9., 10.],
           [12., 13.]],

          [[ 0.,  0.],
           [ 0.,  0.]]],


         [[[ 0.,  0.],
           [ 0.,  0.]],

          [[ 0.,  0.],
           [ 0.,  0.]]]]]])

In [72]:
col.transpose(0, 4, 5, 1, 2, 3)

array([[[[[[ 0.,  0.],
           [ 0.,  0.]],

          [[ 9.,  0.],
           [ 0.,  0.]]],


         [[[ 1.,  0.],
           [ 0.,  0.]],

          [[10.,  0.],
           [ 0.,  0.]]]],



        [[[[ 3.,  0.],
           [ 0.,  0.]],

          [[12.,  0.],
           [ 0.,  0.]]],


         [[[ 4.,  0.],
           [ 0.,  0.]],

          [[13.,  0.],
           [ 0.,  0.]]]]]])

In [73]:
a =  np.zeros((8, 8))

In [74]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
a[0:2:1, 0:2:1]

array([[0., 0.],
       [0., 0.]])