In [44]:
import numpy as np
from common.functions import softmax, cross_entropy_error


class simpleNet:
    def __init__(self):
        self.W = np.array([[1, 2, 3], [4, 5, 6]])

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net = simpleNet()

def f(W):
    print(f"x引数：{x}, t引数:{t}\n")
    print(f"\nparameter: {net.W}\n")
    print("loss:", net.loss(x ,t))
    return net.loss(x, t)
numerical_gradient(f, net.W)


1st_x: [[1 2 3]
 [4 5 6]]
1st_grad: [[0 0 0]
 [0 0 0]]
重み: [[1 2 3]
 [4 5 6]]
h+の重み: [[6 2 3]
 [4 5 6]]
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[6 2 3]
 [4 5 6]]

loss: 0.798915962528734
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[-4  2  3]
 [ 4  5  6]]

loss: 0.20343766922259138
fxh1: 0.798915962528734
fxh2:0.20343766922259138
grad:0
--------------------------------------------------
重み: [[1 2 3]
 [4 5 6]]
h+の重み: [[1 7 3]
 [4 5 6]]
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[1 7 3]
 [4 5 6]]

loss: 1.71045415962476
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[ 1 -3  3]
 [ 4  5  6]]

loss: 0.0591137891832027
fxh1: 1.71045415962476
fxh2:0.0591137891832027
grad:0
--------------------------------------------------
重み: [[1 2 3]
 [4 5 6]]
h+の重み: [[1 2 8]
 [4 5 6]]
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[1 2 8]
 [4 5 6]]

loss: 0.013496161689767772
x引数：[0.6 0.9], t引数:[0 0 1]


parameter: [[ 1  2 -2]
 [ 4  5  6]]

loss: 1.8689804872326186
fxh1: 0.013496161689767772
fxh2:1.8689804872326186
grad:0


array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
# def numerical_gradient(f, x):

def numerical_gradient(f, x):
    h = 5 # 0.0001
    grad = np.zeros_like(x)
    print("1st_x:", x)
    print("1st_grad:", grad)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        print("重み:", x)
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = tmp_val + h
        print("h+の重み:", x)
        fxh1 = f(x) # f(x+h)

        
        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)
        print(f"fxh1: {fxh1}\nfxh2:{fxh2}\ngrad:{grad[idx]}")
        print("-"*50)
        
        x[idx] = tmp_val # 値を元に戻す
        it.iternext()   
        
    return grad

In [9]:
net.W

array([[0.59737388, 2.22724245, 0.55882255],
       [1.21546933, 0.77020211, 0.33265003]])