In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch 
from torch import nn
import torchvision

画像分類のチューニング手法  
・ニューラルネットワークの多層化  
・最適化関数の改善  
・過学習対策 

## ドロップアウト

In [40]:
# ダミーデータの準備
torch.manual_seed(123)
inputs = torch.randn((1, 10))
inputs

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
          0.3239, -0.1085]])

In [41]:
# ドロップアウト
dropout = nn.Dropout(p=0.5)

# 訓練フェーズ
dropout.train()
print(dropout.training)

outputs = dropout(inputs)
print(outputs)
no_drop=torch.sum(outputs==0).item()
print(f'ドロップされていない数: {no_drop}')

print("\n=====================\n")

# 予想フェーズ
dropout.eval()
print(dropout.training)
output = dropout(inputs)
print(output)
no_drop=torch.sum(output==0).item()
print(f'ドロップされていない数: {no_drop}')

True
tensor([[-0.0000,  0.2407, -0.0000, -0.4808, -0.0000,  0.0000, -1.9447, -0.0000,
          0.6478, -0.2170]])
ドロップされていない数: 5


False
tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
          0.3239, -0.1085]])
ドロップされていない数: 0


＜Point＞  
・drop比率を0.5に指定したから正確に10中5個ドロップされるわけではない。 -> どの程度の確率でドロップするかの意味  
・0でない値は1/(1-p)を掛けて、入力値全体のの平均がドロップアウト後も変わらないようにしている。
・過学習には強いが、学習にかかる時間が長くなる。

## Batch Normalization

＜Point＞  
・畳み込みではnn.BatchNorm2d, 線形ではnn.Batch1dを利用  
・インスタンス生成時に必要な引数　2d -> 入力データのチャネル数, 1d -> 入力データの次元数  
・学習対象パラメータにweightとbiasがある。  
・訓練フェーズと予想フェーズで挙動が異なる。  
 

## Data Augmentation

＜Point＞  
・Transformsで実装する
・使用するData Augmentationによって入力データの形式が異なるので注意

In [77]:
test_cov = nn.Conv2d(1, 1, 1, padding=(2, 1))

In [78]:
test_input = torch.randn((1, 1, 1))

In [79]:
test_cov(test_input)

tensor([[[0.3550, 0.3550, 0.3550],
         [0.3550, 0.3550, 0.3550],
         [0.3550, 0.9713, 0.3550],
         [0.3550, 0.3550, 0.3550],
         [0.3550, 0.3550, 0.3550]]], grad_fn=<SqueezeBackward1>)

In [80]:
test_input

tensor([[[1.0080]]])

In [81]:
test_cov.weight

Parameter containing:
tensor([[[[0.6115]]]], requires_grad=True)

In [82]:
test_cov.bias

Parameter containing:
tensor([0.3550], requires_grad=True)